server:
  port: 8080

spring:
  profiles.active: dev
  main:
    banner-mode: off

  application:
    name: wallet-task

#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wallet-task
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mybatis:
    mapper-locations: classpath:mapper/*.xml

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
