server:
  port: 8080

spring:
  profiles.active: dev
  main:
    banner-mode: off

  application:
    name: wallet-task

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    schema: ${DATABASE_SCHEMA}
